services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEBUG=true
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/localstack
    
