services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    restart: always
    hostname: "gitlab.com"
    shm_size: "2gb"
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "100"
    
