version: "3.9"

services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    restart: always
    hostname: "gitlab.luhavis.dev"
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8880:80"
      - "8443:443"
      - "8222:22"
    volumes:
      - "./config:/etc/gitlab:Z"
      - "./logs:/var/log/gitlab:Z"
      - "./data:/var/opt/gitlab:Z"
