 version: "3.9"
  2 services:
  3   mongo:
  4     image: mongo:6.0
  5     restart: unless-stopped
  6     ports:
  7       - "27017:27017"
  8     environment:
  9       - MONGO_INITDB_ROOT_USERNAME=mongo
 10       - MONGO_INITDB_ROOT_PASSWORD=mongo
 11     volumes:
 12       - ./db:/data/db
