version: "3.9"
services:
  fluentd:
    build: ./fluentd
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - es-network
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    ports:
      - "19200:9200"
      - "19600:9600"
    environment:
      - discovery.type=single-node
      - opendistro_security.disabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-network
  kibana:
    build:
      dockerfile: kibana.Dockerfile
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-network

volumes:
  es-data:

networks:
  es-network: