services:
  pypiserver:
    image: pypiserver/pypiserver:v2.3
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - "./packages:/data/packages"
      - "./.htpasswd:/data/auth/.htpasswd"
    command: run -p 8080 -a 'download, list, update' -P /data/auth/.htpasswd/htpasswd.txt /data/packages &
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
