version: "3.9"
services:
  nifi:
    image: apache/nifi:1.22.0
    container_name: nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=docker
      - SINGLE_USER_CREDENTIALS_PASSWORD=testtesttesttest
      - TZ=Asia/Seoul
    volumes:
      - ./data:/data
    ports:
      - 8443:8443
