services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
    privileged: true
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
