services:
  portainer:
    image: portainer/portainer:1.24.2-alpine
    restart: always
    ports:
      - 8880:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data