version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
      - POSTGRES_USER=docker
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
